import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

export default function AdmissionsPage(){
  const steps=["Online Registration","Application Submission","Document Review","Fee Payment & Confirmation"];
  return <main><SiteHeader/>
  <section className="page-hero py-24 text-white"><div className="container-shell"><div className="eyebrow !text-[#e5c47d]">Admissions 2026-27</div><h1 className="serif mt-4 text-5xl font-bold md:text-6xl">Start your Sengol journey.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">A simple, transparent and student-friendly admission process with merit-based, entrance-based, direct and lateral-entry pathways where applicable.</p></div></section>
  <section className="section-pad"><div className="container-shell"><div className="grid gap-5 md:grid-cols-4">{steps.map((s,i)=><div key={s} className="rounded-3xl bg-white p-6 soft-shadow"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#13233f] font-bold text-[#e5c47d]">{i+1}</div><h2 className="serif mt-5 text-xl font-bold text-[#13233f]">{s}</h2></div>)}</div></div></section>
  <section className="section-pad border-y border-[#eadfce] bg-[#fffaf2]"><div className="container-shell grid gap-8 lg:grid-cols-3"><article className="rounded-3xl border border-[#eadfce] bg-white p-7"><h2 className="serif text-2xl font-bold text-[#13233f]">Merit-Based Admission</h2><p className="mt-3 leading-7 text-[#687080]">Selection based on academic performance and merit in the qualifying examination.</p></article><article className="rounded-3xl border border-[#eadfce] bg-white p-7"><h2 className="serif text-2xl font-bold text-[#13233f]">Entrance-Based Admission</h2><p className="mt-3 leading-7 text-[#687080]">Relevant programs may use prescribed entrance examinations as part of selection.</p></article><article className="rounded-3xl border border-[#eadfce] bg-white p-7"><h2 className="serif text-2xl font-bold text-[#13233f]">Scholarships</h2><p className="mt-3 leading-7 text-[#687080]">Merit-based, need-based and category-specific financial support options are available subject to university rules.</p></article></div></section>
  <section id="apply" className="section-pad"><div className="container-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><div className="eyebrow">Application Form</div><h2 className="section-title">Request admission information.</h2><p className="section-copy">This starter form is UI-ready. The database/API wiring is prepared in the project architecture and can be connected next.</p><div className="mt-8 rounded-3xl bg-[#13233f] p-6 text-white"><div className="font-bold text-[#e5c47d]">Admissions Help</div><a className="mt-3 block text-white/75" href="tel:+919205299887">+91 92052 99887</a><a className="mt-2 block text-white/75" href="mailto:admission@sengolinternationaluniversity.edu.in">admission@sengolinternationaluniversity.edu.in</a></div></div><form className="grid gap-4 rounded-[30px] bg-white p-7 soft-shadow md:grid-cols-2"><input className="form-control" placeholder="Full Name"/><input className="form-control" placeholder="Father's Name"/><input className="form-control" type="email" placeholder="Email ID"/><input className="form-control" placeholder="Mobile Number"/><select className="form-control"><option>Program Type</option><option>Undergraduate</option><option>Postgraduate</option><option>Doctoral</option></select><input className="form-control" placeholder="Preferred Course"/><input className="form-control" placeholder="State"/><input className="form-control" placeholder="District"/><button type="button" className="btn-maroon md:col-span-2">Submit Application</button></form></div></section>
  <SiteFooter/></main>
}
