import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import Link from "next/link";

const schools=["Engineering & Technology","Commerce and Management Studies","Computer Science & IT","Architecture & Planning","Hotel Management","Library & Information Science","Science","Arts and Social Studies","Education and Physical Education","Journalism & Mass Media Communication","Law","Allied and Healthcare Sciences","Philosophy and Research","Fire & Safety","Animation","Vocational Studies","Pharmacy"];

export default function ProgramsPage(){return <main><SiteHeader/>
<section className="page-hero py-24 text-white"><div className="container-shell"><div className="eyebrow !text-[#e5c47d]">Academics</div><h1 className="serif mt-4 text-5xl font-bold md:text-6xl">Programs & Schools</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Explore technical, professional, creative, scientific and research-focused academic pathways offered across the university.</p></div></section>
<section className="section-pad"><div className="container-shell"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{schools.map((s,i)=><article key={s} className="card-lift rounded-3xl border border-[#eadfce] bg-white p-7"><div className="mb-5 text-xs font-extrabold uppercase tracking-[.2em] text-[#a8792d]">School {String(i+1).padStart(2,"0")}</div><h2 className="serif text-2xl font-bold text-[#13233f]">School of {s}</h2><p className="mt-3 leading-7 text-[#687080]">Industry-relevant learning with academic foundations, practical exposure and future-focused skills.</p><Link href="/admissions" className="mt-6 inline-block font-bold text-[#7a1f2d]">Admission information →</Link></article>)}</div></div></section>
<section className="section-pad bg-[#13233f] text-white"><div className="container-shell grid gap-8 lg:grid-cols-2 lg:items-center"><div><div className="eyebrow !text-[#e5c47d]">Featured Example</div><h2 className="serif mt-3 text-4xl font-bold">School of Science</h2><p className="mt-5 text-lg leading-8 text-white/70">The School of Science includes programs such as B.Sc. Physics, Chemistry, Biology, Mathematics and Environmental Science, with emphasis on scientific foundations, analysis, laboratory work and research capability.</p></div><div className="rounded-3xl border border-white/10 bg-white/5 p-7"><div className="grid gap-3 text-sm text-white/75">{["B.Sc. Physics · 6 Semesters","B.Sc. Chemistry · 6 Semesters","B.Sc. Biology · 6 Semesters","B.Sc. Mathematics · 6 Semesters","B.Sc. Environmental Science · 6 Semesters"].map(x=><div key={x} className="rounded-xl bg-white/5 px-4 py-3">{x}</div>)}</div></div></div></section>
<SiteFooter/></main>}
